build:
  dependencies:
    before:
      - npm install
  paths:
    - backend/
  nodes:
    coverage:
      tests:
        override:
          - command: npm run test
            coverage:
              file: coverage/clover.xml
              format: clover