build:
  dependencies:
    before:
      - cd backend && npm install
  nodes:
    coverage:
      tests:
        override:
          - command: cd backend && npm run test
            coverage:
              file: backend/coverage/clover.xml
              format: clover