services:
  app:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app/backend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: node server.js