networks:
  vteam:
    driver: bridge

services:
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile

    working_dir: /backend
    volumes:
      - ./backend:/backend
      - ./.env:/backend/.env
    ports:
      - "1337:1337"
    expose:
      - "1337"
    command: node server.js
    networks:
      vteam:
    restart: always

  bikes:
    container_name: bikes
    build:
      context: ./backend/bike
      dockerfile: Dockerfile
    working_dir: /backend/bike
    volumes:
      - ./backend:/backend
      - ./.env:/backend/.env
    networks:
      - vteam
    restart: always

  mobile_app:
    container_name: mobile_app
    build:
      context: ./frontend/mobileapp
      dockerfile: Dockerfile
    volumes:
      - ./frontend/mobileapp:/frontend/mobileapp
    ports:
      - "3001:3001"
    networks:
      - vteam
    restart: always

  web_app:
    container_name: web_app
    build:
      context: ./frontend/webapp
      dockerfile: Dockerfile
    working_dir: /frontend/webapp
    volumes:
      - ./frontend/webapp:/frontend/webapp
      - ./.env:/frontend/webapp/.env
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - vteam
    restart: always
