networks:
  vteam:
services:
  server:
    build:
      context: .
      dockerfile: backend/Dockerfile
      container_name: "server"
    working_dir: /app/backend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "1337:1337"
    command: node server.js
    networks:
      vteam:
    restart:
      "always"
  mobile_app:
  web_interface:
